
export const booksByMood = {
  joyful: ["سعادة", "مرح", "تفاؤل", "حماس", "امتنان",
           "Happiness", "Joy", "Optimism", "Excitement", "Gratitude" ,
           "Bonheur", "Joie", "Optimisme", "Excitation", "Gratitude" ,
           "Felicidad", "Alegría", "Optimismo", "Entusiasmo", "Gratitud",
           "Glück", "Freude", "Optimismus", "Begeisterung", "Dankbarkeit",
           "Felicità", "Gioia", "Ottimismo", "Entusiasmo", "Gratitudine",
           "Mutluluk", "Neşe", "İyimserlik", "Heyecan", "Minnettarlık",
           "快乐", "喜悦", "乐观", "兴奋", "感恩",
           "幸福", "喜び", "楽観", "興奮", "感謝" , 
           "행복", "기쁨", "낙관", "흥분", "감사" , 
           "Счастье", "Радость", "Оптимизм", "Восторг", "Благодарность" 
          ],
  peaceful: ["هدوء", "راحة", "طمأنينة", "تأمل", "انسجام" , 
             "Calm", "Peace", "Tranquility", "Meditation", "Harmony",
             "Calme", "Paix", "Tranquillité", "Méditation", "Harmonie",
             "Calma", "Paz", "Tranquilidad", "Meditación", "Armonía" ,
             "Ruhe", "Frieden", "Gelassenheit", "Meditation", "Harmonie" ,
             "Calma", "Pace", "Tranquillità", "Meditazione", "Armonia" ,
             "Sakinlik", "Huzur", "Dinginlik", "Meditasyon", "Uyum" ,
             "平静", "和平", "宁静", "冥想", "和谐" ,
             "静けさ", "平和", "安らぎ", "瞑想", "調和" ,
             "평온", "평화", "고요", "명상", "조화" ,
             "Спокойствие", "Мир", "Покой", "Медитация", "Гармония"
  ],
  romantic: ["حب", "شغف", "اشتياق", "حنين", "عاطفة" ,
            "Love", "Passion", "Longing", "Nostalgia", "Affection" ,
            "Amour", "Passion", "Désir", "Nostalgie", "Affection" ,
            "Amor", "Pasión", "Anhelo", "Nostalgia", "Afecto" ,
            "Liebe", "Leidenschaft", "Sehnsucht", "Nostalgie", "Zuneigung",
            "Amore", "Passione", "Desiderio", "Nostalgia", "Affetto",
            "Aşk", "Tutku", "Özlem", "Nostalji", "Şefkat",
            "爱", "激情", "思念", "怀旧", "感情",
            "愛", "情熱", "憧れ", "郷愁", "愛情",
            "사랑", "열정", "그리움", "향수", "애정",
            "Любовь", "Страсть", "Тоска", "Ностальгия", "Привязанность"
          ],
  sad: ["حزن", "وحدة", "فقدان", "خيبة أمل", "اشتياق" ,
        "Sadness", "Loneliness", "Loss", "Disappointment", "Longing" ,
         "Tristesse", "Solitude", "Perte", "Déception", "Désir" ,
         "Tristeza", "Soledad", "Pérdida", "Decepción", "Anhelo" ,
         "Traurigkeit", "Einsamkeit", "Verlust", "Enttäuschung", "Sehnsucht" ,
         "Tristezza", "Solitudine", "Perdita", "Delusione", "Desiderio" ,
         "Üzüntü", "Yalnızlık", "Kayıp", "Hayal kırıklığı", "Özlem" ,
         "悲伤", "孤独", "失去", "失望", "思念" ,
         "悲しみ", "孤独", "喪失", "失望", "思い" ,
         "슬픔", "외로움", "상실", "실망", "그리움" ,
         "Печаль", "Одиночество", "Потеря", "Разочарование", "Тоска"
  ],
  curious: ["فضول", "اكتشاف", "تعلم", "استكشاف", "تساؤل" ,
            "Curiosity", "Discovery", "Learning", "Exploration", "Inquiry" ,
            "Curiosité", "Découverte", "Apprentissage", "Exploration", "Questionnement" ,
            "Curiosidad", "Descubrimiento", "Aprendizaje", "Exploración", "Consulta" ,
            "Neugier", "Entdeckung", "Lernen", "Erkundung", "Frage" ,
            "Curiosità", "Scoperta", "Apprendimento", "Esplorazione", "Domanda" ,
            "Merak", "Keşif", "Öğrenme", "Keşfetme", "Sorgulama" ,
            "好奇", "发现", "学习", "探索", "询问" ,
            "好奇心", "発見", "学習", "探検", "質問" ,
            "호기심", "발견", "학습", "탐구", "질문" ,
            "Любопытство", "Открытие", "Обучение", "Исследование", "Вопрос"
  ],
  adventurous: ["مغامرة", "إثارة", "تحدي", "جرأة" ,
                "Adventure", "Excitement", "Challenge", "Courage", "Exploration" ,
                "Aventure", "Excitation", "Défi", "Courage", "Exploration" ,
                "Aventura", "Emoción", "Desafío", "Valentía", "Exploración" ,
                "Abenteuer", "Spannung", "Herausforderung", "Mut", "Erkundung" ,
                "Avventura", "Eccitazione", "Sfida", "Coraggio", "Esplorazione",
                "Macera", "Heyecan", "Meydan okuma", "Cesaret", "Keşif" ,
                "冒险", "刺激", "挑战", "勇气", "探索" ,
                "冒険", "興奮", "挑戦", "勇気", "探検" ,
                "모험", "흥분", "도전", "용기", "탐험" ,
                "Приключение", "Возбуждение", "Вызов", "Смелость", "Исследование"
  ],
  mysterious: ["غموض", "تشويق", "أسرار", "تحقيق" ,
               "Mystery", "Thriller", "Crime", "Investigation", "Horror" ,
               "Mystère", "Suspense", "Crime", "Enquête", "Horreur" ,
               "Misterio", "Suspenso", "Crimen", "Investigación", "Terror" ,
               "Geheimnis", "Thriller", "Krimi", "Ermittlung", "Horror" ,
               "Mistero", "Thriller", "Crimine", "Indagine", "Horror" ,
               "Gizem", "Gerilim", "Suç", "Soruşturma", "Korku" ,
               "悬疑", "惊悚", "犯罪", "调查", "恐怖" ,
               "ミステリー", "スリラー", "犯罪", "調査", "ホラー" ,
               "미스터리", "스릴러", "범죄", "수사", "공포" ,
               "Тайна", "Триллер", "Преступление", "Расследование", "Ужасы"
  ],
  imaginative: ["خيال", "دهشة", "سحر", "إبداع" ,
                "Imagination", "Creativity", "Wonder", "Magic", "Innovation" ,
                "Imagination", "Créativité", "Émerveillement", "Magie", "Innovation" ,
                "Imaginación", "Creatividad", "Asombro", "Magia", "Innovación" ,
                "Vorstellungskraft", "Kreativität", "Wunder", "Magie", "Innovation" ,
                "Immaginazione", "Creatività", "Meraviglia", "Magia", "Innovazione" ,
                "Hayal gücü", "Yaratıcılık", "Hayret", "Büyü", "Yenilik" ,
                "想象力", "创造力", "奇迹", "魔法", "创新" ,
                "想像力", "創造力", "驚き", "魔法", "革新" ,
                "상상력", "창의력", "경이", "마법", "혁신" ,
                "Воображение", "Творчество", "Чудо", "Магия", "Инновация"
  ],
  inspired: ["إلهام", "تحفيز", "طموح", "تطوير الذات", "إنجاز" , 
             "Inspiration", "Motivation", "Ambition", "Achievement", "Growth" ,
             "Inspiration", "Motivation", "Ambition", "Réussite", "Croissance" ,
             "Inspiración", "Motivación", "Ambición", "Logro", "Crecimiento" ,
             "Inspiration", "Motivation", "Ehrgeiz", "Erfolg", "Wachstum" ,
             "Ispirazione", "Motivazione", "Ambizione", "Successo", "Crescita" ,
             "İlham", "Motivasyon", "Hırs", "Başarı", "Gelişim" ,
             "灵感", "激励", "雄心", "成就", "成长" ,
             "インスピレーション", "モチベーション", "野心", "成功", "成長" ,
             "영감", "동기부여", "야망", "성취", "성장" ,
             "Вдохновение", "Мотивация", "Амбиции", "Достижение", "Рост"
  ],
  thoughtful: ["تفكر", "وعي", "حكمة", "فهم الذات" ,
               "Thought", "Wisdom", "Reflection", "Awareness", "Understanding" ,
               "Réflexion", "Sagesse", "Méditation", "Conscience", "Compréhension" ,
               "Reflexión", "Sabiduría", "Meditación", "Conciencia", "Comprensión" ,
               "Nachdenken", "Weisheit", "Reflexion", "Bewusstsein", "Verständnis" ,
               "Riflessione", "Saggezza", "Meditazione", "Consapevolezza", "Comprensione" ,
               "Düşünce", "Bilgelik", "Yansıma", "Farkındalık", "Anlama" ,
               "思考", "智慧", "反思", "意识", "理解" ,
               "思考", "知恵", "熟考", "意識", "理解" ,
               "사고", "지혜", "성찰", "인식", "이해" ,
               "Размышление", "Мудрость", "Рефлексия", "Осознание", "Понимание"
  ]
};